### ISSUE TITLE
Wikitude SDK version

### ISSUE THREAD

**Issue by GianlucaP99** [joaquinlom/react-native-wikitude-sdk#11]
Good morning,
in my tests I followed the procedures for developing wikitude for android and almost everything works, since this is an external plugin, how can I check which version of wikitude sdk I am using and how can I change it?

Thank you.

**Comment by joaquinlom** [comment]
In your experience you can call AR.context.versionNumber https://www.wikitude.com/external/doc/documentation/latest/Reference/JavaScript%20API/classes/context.html

And to modify the version, You need to download the library from Wikitude and replace it in the wikitudeSDK foler. In the next version I'll include the maven support.

**Comment by GianlucaP99** [comment]
Perfect  thank you
