### ISSUE TITLE
NPM package doesn't exist

### ISSUE THREAD

**Issue by Betapig1** [joaquinlom/react-native-wikitude-sdk#12]
When I try to install the npm package is throws an error saying that it doesn't exist. I can't find it on npmjs.com either

**Comment by joaquinlom** [comment]
Hi.
Right now is not under any npm sites, you need to added like this.
"react-native-wikitude-sdk": "github:joaquinlom/react-native-wikitude-sdk",

**Comment by Betapig1** [comment]
Sorry i'm still a bit confused. What am I supposed to use to add it?

**Comment by joaquinlom** [comment]
add that line into the package.json file and run `npm install`
