### ISSUE TITLE
Screen Capture not working

### ISSUE THREAD

**Issue by albanlandry** [joaquinlom/react-native-wikitude-sdk#19]
Hello team,

I am using the react native Wikitude sdk extension with react-native 0.68.2. So far, everything seems to work well. I want to implement the screen capture functionality. However, even the one found in the sample 10_BrowsingPois_6_Bonus-CaptureScreen does not seem to work. Would you please help me on this matter?

Best regards

**Comment by joaquinlom** [comment]
Hi.
Sure, I haven't tested on react-native 0.68. But please, let me know how are you implementing the logic and/or is there a error log when you call the function.

Thanks

**Comment by albanlandry** [comment]
Sorry, I did not follow the example correctly. It is working fine. Is there a way to pass data to the javascript scene?

**Comment by joaquinlom** [comment]
You can use calljavascript to have bidireccional comunication
