### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by JuliaRakitina** [joaquinlom/react-native-wikitude-sdk#2]
Hi, thank you for your work. I was waiting for the new Wikitude-react connector soo long

Please resolve the merge conflict

```
<<<<<<< HEAD
import { NativeModules ,requireNativeComponent ,findNodeHandle,UIManager,PermissionsAndroid,Button, Platform,} from 'react-native';
=======
import { NativeModules ,requireNativeComponent ,findNodeHandle,UIManager,PermissionsAndroid,Button, Platform} from 'react-native';
>>>>>>> 7a80d517418492d323a2b0529e1da11bec307318
```

**Comment by joaquinlom** [comment]
Hi, I just fix the merge conflict.
Thank you

**Comment by JuliaRakitina** [comment]
Dear @joaquinlom actually there not the only one merge conflict in the project please resolve all so I can use the library :)

<img width="1401" alt="Screen Shot 2020-09-29 at 21 23 14" src="https://user-images.githubusercontent.com/4850840/94592378-0e1e0680-029a-11eb-8f50-61cedb7643cc.png">

**Comment by joaquinlom** [comment]
My bad, Sure

**Comment by joaquinlom** [comment]
> Dear @joaquinlom actually there not the only one merge conflict in the project please resolve all so I can use the library :)
> 
> <img alt="Screen Shot 2020-09-29 at 21 23 14" width="1401" src="https://user-images.githubusercontent.com/4850840/94592378-0e1e0680-029a-11eb-8f50-61cedb7643cc.png">

Hi. You can give a Try.
Just I recommend to download the Wikitude SDK IOS, and replace it in the node_modules/react-native-wikitude-sdk/ios folder.

**Comment by JuliaRakitina** [comment]
Hi, I tried Android and it works great! IOS in progress, but no merge conflicts anymore 👍

**Comment by joaquinlom** [comment]
> Hi, I tried Android and it works great! IOS in progress, but no merge conflicts anymore 👍 

Glad to hear that. I'll close this issue.
