### ISSUE TITLE
Is react-native-wikitude package required for react-native-wikitude-sdk?

### ISSUE THREAD

**Issue by vik-addweb** [joaquinlom/react-native-wikitude-sdk#3]
Hi there, 

I'm getting confused about the dependency of the plugin.
As per readme documentation, you have mentioned copy SDK from react-native-wikitude and this plugin's name is react-native-wikitude-sdk. So the question is that typo mistake or I need to copy that from react-native-wikitude ?

cp -R ./node_modules/react-native-wikitude/android/wikitudesdk ./android/wikitudesdk

OR 

cp -R ./node_modules/react-native-wikitude-sdk/android/wikitudesdk ./android/wikitudesdk

@JoaquinSpinar @joaquinlom @notesby

**Comment by joaquinlom** [comment]
@vik-addweb Hi
Yes, it's a typo. The Wikitude SDK downloaded from the SDK page, must be inside the node_modules/react-native-wikitude-sdk/android/wikitudesdk and in the project android folder ./android/wikitudesdk

there is an SDK file in the GitHub but for the size, you should download it from the Wikitude page

**Comment by vik-addweb** [comment]
> ./android/wikitudesdk

Make sense. Thanks @joaquinlom
