### ISSUE TITLE
Android Crash (NullPointerException)

### ISSUE THREAD

**Issue by nocego** [joaquinlom/react-native-wikitude-sdk#6]
Dear Sir

I'm using your wikitude bridge for react-native.
It's working like a charm on iOS. 
But whenever I make a Cloud-Scan on Android, the app crashes. 
With Android Studio I managed to get out the following Error-Message:
![image](https://user-images.githubusercontent.com/44623630/100705798-25679600-33a8-11eb-9e77-6aaca39b44a7.png)

The first Line references to the following Function:
![image](https://user-images.githubusercontent.com/44623630/100705915-547e0780-33a8-11eb-883e-a278fc315238.png)
in the (by Android Studio decompiled) File:
./android/wikitudesdk/build/.transforms/997f22ecd96cb7fdd0c1ebda5cf1d775/jetified-wikitudesdk/jars/classes.jar!/com/wikitude/architect/h.class

I implemented the WikitudeView as following into my class:
```
render() {
    //some code
    return (
        <View style={localStyles.flex}>
            //some code
            <WikitudeView
                style={{ flex: 1 }}
                url={'some-link.com'}
                licenseKey={this.state.licenseKey}
                onJsonReceived={(jsonObject) => {this._onJsonReceived(jsonObject, this.navigation)}}
            />
            //some code
        </View>
    );
}
```

Could You help me with this?

Best Regards

**Comment by joaquinlom** [comment]
Hi.
Can you please tell me what version of the WikitudeSDK are you running, and also if is possible for the JS code to try to replicate (whitout keys)
I tested on my own cloud scan and is working.

**Comment by nocego** [comment]
Thank you very much for your response.

- I tried with the wikitudeSDK you provide in this repo _(copied the files in node_modules/react-native-wikitude-sdk/android/wikitudesdk to android/wikitudesdk)_
- I also tried wikitudeSDK v9.5 and v9.3.0 _(just replaced wikitudesdk.aar and build.gradle in android/wikitudesdk/ with the files  from Examples/SDKExamples/wikitude-sdk)_

JSCode:
```
import React, { Component } from 'react';

import {WikitudeView} from 'react-native-wikitude-sdk';

export default class ARScan extends Component{
    constructor(props) {
        super();
        this.state = {
            licenseKey : "mylicensekey",
        }
    }

    render() {
        return (
            <WikitudeView
                style={{ flex: 1 }}
                url={'https://url/to/my/cloudtracker/singleCloudTracking/index.html'}
                licenseKey={this.state.licenseKey}
            />
        );
    }
}
```

**Comment by joaquinlom** [comment]
Ok, Does the WikitudeView is rendering(Camera feed), or is happening right out the way when you display that component?.

Does it happen when you start the recognition? or with some other trigger?

Are you using: startContinuousRecognition or single recognition.

**Comment by nocego** [comment]
The WikitudeView is rendering fine. Everything works as excepted until a Marker is recognized.

I'm using `startContinuousRecognition`.

I actually pinned down the error a little bit today:
The error only occures when I use HTMLDrawables. The following Examples all throw the described nullpointer exception:
```
videoDrawable = new Video({loadingDraw: singleCloudTracking.loadingDrawable});
videoDrawable.config.loadingDraw.enabled = true

website = new Website({url: ..., loadingDraw: singleCloudTracking.loadingDrawable});
website.config.loadingDraw.enabled = true

img3dslide = new Image3dSlide({loadingDraw: singleCloudTracking.loadingDrawable});
img3dslide.config.loadingDraw.enabled = true

obj3d = new Obj3D({loadingDraw: singleCloudTracking.loadingDrawable});
obj3d.config.loadingDraw.enabled = true

img3d = new Image3d({loadingDraw: singleCloudTracking.loadingDrawable})
img3d.config.loadingDraw.enabled = true
```
where as `singleCloudTracking.loadingDrawable` is generated from:
```
generateLoadingDrawable: () => {
	return new AR.HtmlDrawable({html: `${World.getExternalHtmlcss()}  
		<div class="loadingDiv" id="loading">
			<div class="indicatorDiv">
				<div class="spinner">
					<div class="rect1"></div>
					<div class="rect2"></div>
					<div class="rect3"></div>
					<div class="rect4"></div>
					<div class="rect5"></div>
				</div>
				<p class="loadingLabel">${World.lText("loading")}</p>
			</div>
		</div>
	`}, 0.5, {
		horizontalAnchor: AR.CONST.HORIZONTAL_ANCHOR.CENTER,
		verticalAnchor: AR.CONST.VERTICAL_ANCHOR.MIDDLE,
		opacity : 1,
		zOrder: 5,
		viewportWidth: 980,
		viewportHeight: 980,
		enabled: false
	});
},
```

But when I comment out the lines resembling `videoDrawable.config.loadingDraw.enabled = true`, it all works fine. But I'm missing the loading drawable obviously.

I also tried to adjust the `generateLoadingDrawable` function. But I don't think the error lies there.

Strangely everything works still great on iOS.

**Comment by joaquinlom** [comment]
Thanks, with that information I can take a look more closely.
Let me do some tests and let you know.

**Comment by joaquinlom** [comment]
Still no response from Wikitude. But I found that issue on IOS as well. and it was using a certain version of the WikitudeSDK.

**Comment by nocego** [comment]
Ok, so you found a way around this problem? I tried to avoid HTMLDrawables in my current project. But to solve the problem would clearly solve some difficulties in upcoming projects.

**Comment by joaquinlom** [comment]
Not yet, I got focused on IOS, and Wikitude Team hasn't replied to our issues with the Framework.

Did you try different Wikitude SDK versions? the 8.9 seems more stable for RN.

https://support.wikitude.com/support/discussions/topics/5000094988
https://support.wikitude.com/support/discussions/topics/5000095807
https://support.wikitude.com/support/discussions/topics/5000095872

**Comment by nocego** [comment]
Thanks for your investigation. Currently I don't have the spare time to test it. But I'll try different versions on my next project. I'll let you know if the problems persist.

Thanks for your help and the plugin in general!
