### ISSUE TITLE
File was not found or file was unreadable. 

### ISSUE THREAD

**Issue by azesmway** [joaquinlom/react-native-wikitude-sdk#9]
Hi
Please help!
There is a problem of working in android

Permanent error - File was not found or file was unreadable. 
I install all data as described in the documentation 

mobile/android/app/src/main/assets/poi/index.html

`const URL_POI = 'poi/index'`

not work in debug and apk

**Comment by joaquinlom** [comment]
Hi.
let me check.
Only offline experience?

**Comment by azesmway** [comment]
Hi
Yes, the data is all in the app

**Comment by azesmway** [comment]
> Hi.
> let me check.
> Only offline experience?

Hi
Yes, the data is all in the app

**Comment by azesmway** [comment]
Your example also does not work on android

**Comment by joaquinlom** [comment]
> Your example also does not work on android

Can you elaborate more?

I don't have problems running the example. Tell me the steps to reproduce.

Thank you

**Comment by azesmway** [comment]
> > Your example also does not work on android
> 
> Can you elaborate more?
> 
> I don't have problems running the example. Tell me the steps to reproduce.
> 
> Thank you

Ok

macOS 11.1
yarn  v1.22.10
Android Studio 4.1.2
Sumsung MS-A415F

git clone https://github.com/joaquinlom/react-native-wikitude-sdk-example.git
yarn install
change license key
run on device in debug mode

1. Error - wikitude.postCreate(); not found
2. Error - E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: com.wikitudeexample.MainActivity cannot be cast to com.reactnativenavigation.NavigationActivity
3. Error log :

E/Wikitude: File was not found or file was unreadable.
D/WikitudeViewManager: Setting url:ARchitectExamples/08_PointOfInterest_3_MultiplePois/index
D/WikitudeView: Es local URL
D/WikitudeView: Setting URL Again
    ARchitectExamples/08_PointOfInterest_3_MultiplePois/index.html
    ARchitectExamples/08_PointOfInterest_3_MultiplePois/index.html
I/ReactNativeJS: { message: 'File was not found or file was unreadable.' }

**Comment by joaquinlom** [comment]
update the wikitudeSDK to fix one error. I-m still working on the file was not found. Because I don;t have device to test it now.

**Comment by azesmway** [comment]
> update the wikitudeSDK to fix one error. I-m still working on the file was not found. Because I don;t have device to test it now.

How to update correctly wikitudeSDK ?

**Comment by joaquinlom** [comment]
Right now I believe is just delete de module folder inside node_modules and run npm install

**Comment by azesmway** [comment]
> It's using the file correctly, it just sends twice the event onFinish.
> 
> _onFinishLoading(event) on Android it might call twice when is a online experience. handles the event when the Experience is finish loading_

Hi

I update, but not work 

`W/wikitudeexampl: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
E/Wikitude: File was not found or file was unreadable.
W/cr_media: Requires BLUETOOTH permission
D/WikitudeViewManager: Setting url:ARchitectExamples/08_PointOfInterest_3_MultiplePois/index
D/WikitudeView: Es local URL
    Setting URL Again
    ARchitectExamples/08_PointOfInterest_3_MultiplePois/index.html
    ARchitectExamples/08_PointOfInterest_3_MultiplePois/index.html
I/ReactNativeJS: { message: 'File was not found or file was unreadable.' }
I/SurfaceView: onWindowVisibilityChanged(0) true com.wikitude.common.rendering.internal.e{aad0c47 V.E...... ......I. 0,0-0,0} of ViewRootImpl@1da94b3[MainActivity]`

**Comment by joaquinlom** [comment]
The error file was not found might happened because like I said it firing the event twice. Can you put an alert in the index.html?, to ensure that no file is loaded.

**Comment by azesmway** [comment]
> The error file was not found might happened because like I said it firing the event twice. Can you put an alert in the index.html?, to ensure that no file is loaded.

Hi
problem with "E/Wikitude: File was not found or file was unreadable." and remained.
but I managed to start displaying on android.

Wikitude android does not know how to determine geolocation and he needs to give it at the start
I used "injectLocation"

thank you for your help!
